#! /bin/sh
# /etc/init.d/iot-setup

DAEMON='/usr/bin/bt.py'
PID='/var/run/bt.pid'
DAEMON2='/usr/bin/zbwardrive.sh'
PID2='/var/run/zbwardrive.pid'

case "$1" in
  start)
    echo "Starting IoT setup process"
    mkdir /tmp/pcaps 2> /dev/null
    touch /tmp/gpsfifo # deliberately not a fifo
    # Start python script to connect to android device
    start-stop-daemon --exec $DAEMON --start --pidfile $PID --background
    # start zbwardrive
    start-stop-daemon --exec $DAEMON2 --start --pidfile $PID2 --background
    ;;
  *)

esac

exit 0
